# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :ovirt3 do |ovirt|
    ovirt.url = "https://ovirt.example.com:443"
    ovirt.username = "Username"
    ovirt.password = "Secret"
    ovirt.datacenter = "Datacenter name"
  end
end
