# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = 'ovirt3'
  config.vm.box_url = 'https://github.com/myoung34/vagrant-ovirt3/blob/master/example_box/dummy.box?raw=true'

  config.vm.provider :ovirt3 do |ovirt|
    ovirt.url = "https://ovirt.example.com:443"
    ovirt.username = "username"
    ovirt.password = "secret"
    ovirt.datacenter = "Datacenter name"
    ovirt.template = "Template name"
    ovirt.quota = "e92124b9-22f4-4cef-bcd6-b9ae22155dcd"
    ovirt.cpus = 1
    ovirt.memory = 512
    ovirt.ca_no_verify = true
  end
end
